// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    _default: typeof import('./layouts/_default.vue')['default']
    _Test: typeof import('./components/recycle bin/_Test.vue')['default']
    AuthenticatedLayout: typeof import('./layouts/AuthenticatedLayout.vue')['default']
    CameraButton: typeof import('./components/CameraButton.vue')['default']
    CardSwiper: typeof import('./components/CardSwiper.vue')['default']
    DatePicker: typeof import('./components/datePicker.vue')['default']
    Day: typeof import('./components/Day.vue')['default']
    Days: typeof import('./components/Days.vue')['default']
    Default: typeof import('./layouts/default.vue')['default']
    Dialog: typeof import('./components/Dialog.vue')['default']
    DoughnutChart: typeof import('./components/DoughnutChart.vue')['default']
    ErrorNotFound: typeof import('./pages/ErrorNotFound.vue')['default']
    EssentialLink: typeof import('./components/EssentialLink.vue')['default']
    Feature: typeof import('./components/Feature.vue')['default']
    Home: typeof import('./pages/Home.vue')['default']
    Item: typeof import('./components/Item.vue')['default']
    JsonSearch: typeof import('./components/JsonSearch.vue')['default']
    KanBan: typeof import('./components/recycle bin/KanBan.vue')['default']
    Month: typeof import('./components/recycle bin/Month.vue')['default']
    'Month copy': typeof import('./components/recycle bin/Month copy.vue')['default']
    MonthOld: typeof import('./components/recycle bin/Month-old.vue')['default']
    MyButton: typeof import('./components/MyButton.vue')['default']
    NavButton: typeof import('./components/recycle bin/NavButton.vue')['default']
    PetCard: typeof import('./components/PetCard.vue')['default']
    PetListItem: typeof import('./components/PetListItem.vue')['default']
    PieChart: typeof import('./components/PieChart.vue')['default']
    ProductCard: typeof import('./components/ProductCard.vue')['default']
    QSortableList: typeof import('./components/recycle bin/QSortableList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SlottedList: typeof import('./components/SlottedList.vue')['default']
    SortableList: typeof import('./components/SortableList.vue')['default']
    SwipableList: typeof import('./components/SwipableList.vue')['default']
    Test: typeof import('./pages/Test.vue')['default']
    TestLayout: typeof import('./layouts/TestLayout.vue')['default']
    UserDashboard: typeof import('./pages/UserDashboard.vue')['default']
    Week: typeof import('./components/recycle bin/Week.vue')['default']
    WeekHeader: typeof import('./components/recycle bin/WeekHeader.vue')['default']
  }
}

export {}
