on: [push]
name: Code references
jobs:
  scan-repo:
    runs-on: ubuntu-latest
    name: Scan repository for code references
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Scan & upload
        uses: configcat/scan-repository@v1
        with:
          api-user: ${{ secrets.CONFIGCAT_API_USER }}
          api-pass: ${{ secrets.CONFIGCAT_API_PASS }}
          config-id: 08da4e36-141c-4dbb-84a7-18fa77a7570a
