on: [push]
name: Code references
jobs:
  scan-repo:
    runs-on: ubuntu-latest
    name: Scan repository for code references
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: secrets-to-env-action
        uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}
